-- 001_initial_schema_rollback.sql
BEGIN;
DROP TABLE IF EXISTS provider_score_snapshots CASCADE;
DROP TABLE IF EXISTS config_versions CASCADE;
DROP TABLE IF EXISTS notification_events CASCADE;
DROP TABLE IF EXISTS notification_templates CASCADE;
DROP TABLE IF EXISTS dispute_actions CASCADE;
DROP TABLE IF EXISTS evidence CASCADE;
DROP TABLE IF EXISTS disputes CASCADE;
DROP TABLE IF EXISTS settlement_legs CASCADE;
DROP TABLE IF EXISTS settlements CASCADE;
DROP TABLE IF EXISTS awards CASCADE;
DROP TABLE IF EXISTS quotes CASCADE;
DROP TABLE IF EXISTS rfqs CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
COMMIT;
